### ISSUE TITLE
Checklist to get this added to Nebari

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari-workflow-controller#13]
- [x] get tests passing
- [x] make a way to disable it via Nebari Config
- [x] add test showing nodeSelectors are passed properly
- [x] test test showing resources are passed properly
- [ ] Write up some docs
  - [x] purpose - validation
  - [x] It's in beta
  - [x] how to disable
  - [x] how to mutate (jupyterflow-override)
    - [x] have to have user pod running
  - [x] limitations
    - [x] doesn't support argo retry or submitting workflows via kubectl.  Does support Argo cli tool, hera, argo workflows python client, etc.
   - [x] CronWorkflows

**Comment by Adam-D-Lewis** [comment]
Added since May release!
